-- MySQL Script generated by MySQL Workbench
-- sex 26 out 2018 15:24:31 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DB_aulas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_aulas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_aulas` DEFAULT CHARACTER SET utf8 ;
USE `DB_aulas` ;

-- -----------------------------------------------------
-- Table `DB_aulas`.`TB_sala`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_aulas`.`TB_sala` (
  `id_sala` INT NOT NULL AUTO_INCREMENT,
  `sala_n` INT NULL,
  PRIMARY KEY (`id_sala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_aulas`.`TB_prof`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_aulas`.`TB_prof` (
  `id_prof` INT NOT NULL AUTO_INCREMENT,
  `prof_nome` VARCHAR(80) NULL,
  `prof_sobrenome` VARCHAR(90) NULL,
  PRIMARY KEY (`id_prof`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_aulas`.`TB_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_aulas`.`TB_curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `curso_nome` VARCHAR(100) NULL,
  `curso_inicio` VARCHAR(45) NULL,
  `curso_fim` VARCHAR(45) NULL,
  `sala_id` INT NULL,
  `prof_id` INT NULL,
  PRIMARY KEY (`id_curso`),
  INDEX `fk_TB_curso_TB_sala_idx` (`sala_id` ASC),
  INDEX `fk_TB_curso_TB_prof1_idx` (`prof_id` ASC),
  CONSTRAINT `fk_TB_curso_TB_sala`
    FOREIGN KEY (`sala_id`)
    REFERENCES `DB_aulas`.`TB_sala` (`id_sala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TB_curso_TB_prof1`
    FOREIGN KEY (`prof_id`)
    REFERENCES `DB_aulas`.`TB_prof` (`id_prof`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `DB_aulas`.`TB_sala`
-- -----------------------------------------------------
START TRANSACTION;
USE `DB_aulas`;
INSERT INTO `DB_aulas`.`TB_sala` (`id_sala`, `sala_n`) VALUES (1, 401);
INSERT INTO `DB_aulas`.`TB_sala` (`id_sala`, `sala_n`) VALUES (2, 402);
INSERT INTO `DB_aulas`.`TB_sala` (`id_sala`, `sala_n`) VALUES (3, 403);
INSERT INTO `DB_aulas`.`TB_sala` (`id_sala`, `sala_n`) VALUES (4, 404);
INSERT INTO `DB_aulas`.`TB_sala` (`id_sala`, `sala_n`) VALUES (5, 405);
INSERT INTO `DB_aulas`.`TB_sala` (`id_sala`, `sala_n`) VALUES (6, 406);
INSERT INTO `DB_aulas`.`TB_sala` (`id_sala`, `sala_n`) VALUES (7, 407);
INSERT INTO `DB_aulas`.`TB_sala` (`id_sala`, `sala_n`) VALUES (8, 408);
INSERT INTO `DB_aulas`.`TB_sala` (`id_sala`, `sala_n`) VALUES (9, 409);
INSERT INTO `DB_aulas`.`TB_sala` (`id_sala`, `sala_n`) VALUES (10, 410);

COMMIT;


-- -----------------------------------------------------
-- Data for table `DB_aulas`.`TB_prof`
-- -----------------------------------------------------
START TRANSACTION;
USE `DB_aulas`;
INSERT INTO `DB_aulas`.`TB_prof` (`id_prof`, `prof_nome`, `prof_sobrenome`) VALUES (1, 'Roberto', 'Santos');
INSERT INTO `DB_aulas`.`TB_prof` (`id_prof`, `prof_nome`, `prof_sobrenome`) VALUES (2, 'Christian', 'Ornellas');
INSERT INTO `DB_aulas`.`TB_prof` (`id_prof`, `prof_nome`, `prof_sobrenome`) VALUES (3, 'Álvares', 'de Azevedo');
INSERT INTO `DB_aulas`.`TB_prof` (`id_prof`, `prof_nome`, `prof_sobrenome`) VALUES (4, 'Mario', 'de Andrade');
INSERT INTO `DB_aulas`.`TB_prof` (`id_prof`, `prof_nome`, `prof_sobrenome`) VALUES (5, 'Mário', 'Quintana');

COMMIT;

