version: '3.7'

services:
  adonis-demo-api:
    container_name: adonis-demo-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3333:3333'
    expose:
      - '3333'
    depends_on:
      - db
    links:
      - db

  db:
    container_name: adonis-demo-db
    image: postgres:12.2-alpine
    ports:
      - '5432:5432'
    expose: 
      - '5432'
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo1234
      POSTGRES_HOST_AUTH_METHOD: trust
